services:
  # 1. Backend (Express)
  - type: web
    name: sport-complex-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js

  # 2. Frontend (Vite)
  - type: web
    name: sport-complex-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
